#!/usr/bin/env python3
"""
build.py
-----------------------------------------------------------------------
Regenerates index.html from the modular source files (styles.css and
js/**/*.js).

Why this exists: index.html is a single, fully self-contained file (CSS
and JS inlined directly into it) so the app works from a plain
double-click, with no server and no build step for END USERS. But that
means index.html is a *generated* file - the real source of truth is
styles.css and the files under js/.

Whenever you edit styles.css or anything under js/, run this script to
regenerate index.html:

    python3 build.py

This has no dependencies beyond Python 3's standard library.
-----------------------------------------------------------------------
"""

from pathlib import Path

ROOT = Path(__file__).parent

# Order matters: later files can reference globals defined by earlier
# ones (e.g. app.js uses compareDatasets from compareEngine.js). These
# are plain <script> tags sharing one global scope, not ES modules.
LOCAL_SCRIPTS = [
    ("js/parsers.js", None),
    ("js/compareEngine.js", None),
    ("js/exportCsv.js", None),
    ("js/exportExcel.js", None),
    ("js/components/FileUploadCard.js", "text/babel"),
    ("js/components/OptionsPanel.js", "text/babel"),
    ("js/components/SummaryBar.js", "text/babel"),
    ("js/components/ResultsTable.js", "text/babel"),
    ("js/app.js", "text/babel"),
]

SHELL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Spreadsheet Diff — Compare CSV & Excel Files</title>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Inter:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">

<style>
__CSS__
</style>
</head>
<body>

<div id="root"></div>

<!-- Third-party libraries (all client-side, no build step required for
     the app itself - this script is only for stitching OUR OWN files
     together during development). -->
<script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
<script src="https://unpkg.com/papaparse@5.4.1/papaparse.min.js"></script>
<script src="https://unpkg.com/xlsx@0.18.5/dist/xlsx.full.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/exceljs/4.4.0/exceljs.min.js"></script>

<!-- App code: inlined directly (not loaded via local src=) so the page
     works as a single, fully self-contained file - even if it's moved,
     previewed, or opened on its own without the rest of the project
     folder alongside it. Generated by build.py - do not hand-edit the
     script/style blocks below; edit styles.css / js/**/*.js instead. -->
__SCRIPTS__

</body>
</html>
"""


def build():
    css = (ROOT / "styles.css").read_text()

    blocks = []
    for rel_path, script_type in LOCAL_SCRIPTS:
        content = (ROOT / rel_path).read_text()
        type_attr = f' type="{script_type}"' if script_type else ""
        blocks.append(f"<script{type_attr}>\n{content}\n</script>")

    html = SHELL.replace("__CSS__", css).replace("__SCRIPTS__", "\n\n".join(blocks))
    (ROOT / "index.html").write_text(html)
    print(f"Wrote index.html ({len(html):,} bytes) from styles.css + {len(LOCAL_SCRIPTS)} script(s).")


if __name__ == "__main__":
    build()
